openapi: 3.0.0
info:
  title: Lion Parcel API
  description: API Documentation for Lion Parcel including User, Movie, and Admin endpoints.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:9001
paths:
  /user/registration:
    post:
      summary: User Registration
      description: Endpoint untuk mendaftarkan pengguna baru.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: hedy
                password:
                  type: string
                  example: hedy
                email:
                  type: string
                  example: hedy@gmail.com
                isAdmin:
                  type: boolean
                  example: true
      responses:
        200:
          description: User registered successfully.
  /user/login:
    post:
      summary: User Login
      description: Endpoint untuk masuk sebagai pengguna.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: hedy@gmail.com
                password:
                  type: string
                  example: hedy
      responses:
        200:
          description: Login successful.
  /user/logout:
    post:
      summary: User Logout
      description: Endpoint untuk keluar dari sistem.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Logout successful.
  /movie:
    get:
      summary: Get Movie List
      description: Endpoint untuk mendapatkan daftar film.
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          schema:
            type: integer
            example: 4
      responses:
        200:
          description: A list of movies.
  /movie/search:
    get:
      summary: Search Movies
      description: Endpoint untuk mencari film berdasarkan kata kunci.
      parameters:
        - name: search
          in: query
          schema:
            type: string
            example: "action"
      responses:
        200:
          description: Search results.
  /movie/{movieId}/watch:
    get:
      summary: Watch Movie
      description: Endpoint untuk menonton film.
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: string
            example: 74c1396e-1b9c-4926-9523-fbb4c4abad6f
      responses:
        200:
          description: Streaming movie.
  /movie/{movieId}/vote:
    post:
      summary: Vote for Movie
      description: Endpoint untuk memberikan suara pada film.
      security:
        - bearerAuth: []
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: string
            example: 5180f53b-c6c3-4243-8c93-5b77333e2bce
      responses:
        200:
          description: Vote successful.
  /movie/voted:
    get:
      summary: Get Voted Movies
      description: Endpoint untuk mendapatkan daftar film yang di-vote.
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of voted movies.
  /admin/movie:
    post:
      summary: Create Movie
      description: Endpoint untuk membuat film baru.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                movie:
                  type: string
                  example: "{\"title\": \"End Game\", \"description\": \"Fighting with Thanos\", \"genres\": [\"action\", \"romance\"], \"artists\": [\"hedy\"], \"duration\": \"300\"}"
                video:
                  type: string
                  format: binary
      responses:
        200:
          description: Movie created successfully.
  /admin/top-viewed:
    get:
      summary: Get Top Viewed Movies
      description: Endpoint untuk mendapatkan daftar film yang paling banyak ditonton.
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of top viewed movies.
